global using Microsoft.UI;
global using Microsoft.UI.Dispatching;
global using Microsoft.UI.Windowing;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Media.Animation;
global using System;
global using X.Infrastructure.Caching;
global using X.Infrastructure.Caching.Core;